Wereld scherm
IctoriaBV/FixjeOPP pull request #4
Opened 2024-06-19 08:27 UTC by jaffryhossain

Ronde buttons gemaakt die naar een term pagina gaan. Geen UML, wordt aangeleerd.

2024-06-19 10:05 UTC, Verdi-B requested changes

2024-06-19 10:05 UTC, Verdi-B commented on ViewModels/WorldScreenViewModel.cs
> +            NavigateCommand = new Command<string>(async (term) => await NavigateToTerm(term));
In geval van een command zou je ook in plaats van de gebruikte oplossing de volgende tag kunnen gebruiken: [RelayCommand]. Dit is niet fout maar het is iets wat mij opviel.

2024-06-19 10:05 UTC, Verdi-B commented on Views/Term1Page.xaml
> +<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
Zou ik de aaname mogen maken dat alle termPage  files later weg gaan voor wanneer we de data hebben?

2024-06-19 10:05 UTC, Verdi-B commented on Views/WorldScreen.xaml.cs
> +        public WorldScreen()
Dit hoort eigenlijk anders. Je hoort hierbij de ViewModel door te geven als een parameter van de constructor en deze dan aan BindingContext door geven

2024-06-19 10:06 UTC, Verdi-B commented on Views/WorldScreen.xaml.cs
> +        public WorldScreen()
Alleen dit hoeft veranderd te worden in mijn ogen
Wel op de andere gemaakte commentaar antwoorden

2024-06-20 07:42 UTC, jaffryhossain commented on ViewModels/WorldScreenViewModel.cs
> +            Terms = new ObservableCollection<Term>
Ik ga er naar kijken wat ik hierin kan loopen maar sommige dingen kunnen hier in volgens mij niet gelooped worden.
Name = "Term 1", CommandParameter = "Term1", Index = 0, ImageSource = "icon_wereld.png"
de Name en ImageSource zijn voor elke term natuurlijk anders

2024-06-20 07:42 UTC, jaffryhossain commented on ViewModels/WorldScreenViewModel.cs
> +            NavigateCommand = new Command<string>(async (term) => await NavigateToTerm(term));
Geen idee wat je hier mee bedoelt maar ik ga het ook nakijken en anders stel ik jou hier maandag een vraag over.

2024-06-20 07:44 UTC, jaffryhossain commented on Views/Term1Page.xaml
> +<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
Ja, ik denk wel dat die TermXPage.xaml uiteindelijk allemaal verwijderd worden en dat er 1 termpage komt waar de info en afbeeldingen dynamisch in komen afhankelijk van welke knop je hebt aangedrukt.

Maar als ik eerlijk ben heb ik nog geen idee hoe ik dat moet realiseren.

2024-06-20 07:49 UTC, jaffryhossain commented on Views/WorldScreen.xaml.cs
> +        public WorldScreen()
Hier zou ik graag maandag ook wat meer over weten wat je hier precies mee bedoelt.

2024-06-26 08:54 UTC, merged